package config

var (
	// NATSADDR ...
	NATSADDR = "nats://192.168.2.198:4222"
	// HTTPADDR ...
	HTTPADDR = "localhost:8888"
	// CRTFILE ...
	CRTFILE = "../cert/server.crt"
	// KEYFILE ...
	KEYFILE = "../cert/server.key"
)
