package config

var (
	// HTTPADDR ...
	HTTPADDR = "0.0.0.0:80"
	// CRTFILE ...
	CRTFILE = "../cert/server.crt"
	// KEYFILE ...
	KEYFILE = "../cert/server.key"
	// RTMPURL ...
	RTMPURL = "/movie"
	// FLVURL ...
	FLVURL = "/mt/movie"
	// PUBLISHSECRET ...
	PUBLISHSECRET = "nicetry"
)
