package config

var (
	// HTTPADDR ...
	HTTPADDR = "0.0.0.0:8888"
	// CRTFILE ...
	CRTFILE = "../cert/server.crt"
	// KEYFILE ...
	KEYFILE = "../cert/server.key"
	// RTMPURL ...
	RTMPURL = "/movie"
	// PUBLISHSECRET ...
	PUBLISHSECRET = "nicetry"
	// PREFIXURI ...
	PREFIXURI = "/mt"
)
